# configure your datasource
quarkus.datasource.db-kind = mysql
quarkus.datasource.username = root
quarkus.datasource.password = andrestorres
quarkus.datasource.jdbc.url = jdbc:mysql://localhost:3306/todogrupo2

# drop and create the database at startup (use `update` to only update the schema)
quarkus.hibernate-orm.schema-management.strategy = update
firebase.credentials=src/main/resources/todogrupo2-dd9dd-firebase-adminsdk-fbsvc-df883834d9.json